import Head from "next/head";

const MetaHead = () => {
    return (
       <Head>
        <title>Trip Buddy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    )
}

export default MetaHead